### ISSUE TITLE
Нерабочая ссылка в ДЗ модуля 1

### ISSUE THREAD

**Issue by Chettto** [Data-Learn/data-engineering#68]
В файле readme.md [ДЗ модуля 1 ](https://github.com/Data-Learn/data-engineering/tree/master/DE-101%20Modules/Module01/DE%20-%20101%20Lab%201.1#%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B4%D0%BB%D1%8F-%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8F-1)
Не работают ссылки с примерами в самом низу страницы

- [пример отчета](https://github.com/Data-Learn/data-engineering/blob/master/DE-101/Module-01/Lab/Sample%20-%20Superstore%20-%20Dashboard.xlsx)
- [пошаговая инструкция](https://github.com/Data-Learn/data-engineering/blob/master/DE-101/Module-01/Lab/build_steps_dashboard.md)

**Comment by hello-datalearn** [comment]
Fixed.
